# I used https://github.com/soracqt/myarch as a reference.
# Thanks to soracqt(https://github.com/soracqt).

name: Build Uhuru Image Yor

on:
  pull_request:
    branches: [ dev ]

  schedule:
    - cron: '0 1,6,9,11,13,16,19,21,23 1,3,4,6,8,11,14,16,18,20,24,26 * 1-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:20221030
      volumes:
        - /home/runner/work/uhurudir/uhurudir:/tmp/uhurudir
      options: "--privileged"

    steps:

      - uses: actions/checkout@v3
      
      - name: Fasttrack
        run: |
          pacman-mirrors --fasttrack

      - name: Install Required Packages
        run: |
          pacman -Syyu --noconfirm zsh wget git make sudo python3 base-devel cmake ninja qt5-base arch-install-scripts pyalpm squashfs-tools libisoburn dosfstools   

      - name: Install BlackArch keys and Fetch blackarc-mirrorlist
        run: |
          wget https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz && \
          pacman --noconfirm -U blackarch-keyring.pkg.tar.xz
          wget -P /etc/pacman.d/ https://blackarch.org/blackarch-mirrorlist

      - name: Populate keyrings
        run: |
          pacman-key --init
          pacman-key --populate manjaro blackarch

      - name: Build UhuruOS Yor edition
        run: ./build.sh -c zstd --noloopmod --noconfirm --cleanup xfce_yor
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uhuru_x86_64
          path: out

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')_Yor"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: uhuru_x86_64
          
      - name: Install jq
        run: sudo apt install jq

      - name: Upload to anonfiles
        id: uploadiso
        run: echo "::set-output name=url::Please Download ISO from releases or $(curl -s --retry 3 -F file=@`echo UhuruOS-*-x86_64.iso` https://api.anonfiles.com/upload | jq .data.file.url.short )"

      - name: Split ISO Images
        run: |
          ls UhuruOS-xfce_yor-en-*.iso | xargs -n1 -I{} bash -c "split -b1500m {} {}_splitted_ ; rm {}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          body: ${{steps.uploadiso.outputs.url}}
          draft: false
          prerelease: false
          files: |
           UhuruOS-*x86_64.iso_splitted_*


